FROM wordpress:php8.2-fpm

# Устанавливаем WP-CLI
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

# Создаем alias для wp-cli с --allow-root
RUN echo '#!/bin/bash' > /usr/local/bin/wp-cli && \
    echo 'wp --allow-root "$@"' >> /usr/local/bin/wp-cli && \
    chmod +x /usr/local/bin/wp-cli
